### ISSUE TITLE
Lost lives reappear in the next level

### ISSUE THREAD

**Issue by radharai** [prepitt/bubble#18]
Steps 
a. Played level 25 which was timed. I lost and Game replay button appeared. 
b. I clicked on "Game replay" and started to play level 25 again. I lost again. 
c. I clicked on "Game replay" button and started to play level 25 again. I passed the level this time and moved on to level 26
d. All 2 lives that I lost in my previous level reappeared. Meaning I saw all 3 lives instead of just one live.

**Comment by Navjotkaur12** [comment]
This was done so that kids can have atleast 3 chances to play each level, but if you want to change this scenario , then i will do it so.
