### ISSUE TITLE
Level 31 doesn't show up any goal

### ISSUE THREAD

**Issue by radharai** [prepitt/bubble#19]
Steps:

 I played till level 30 and clicked on level 31. Level 31 doesn't show up any goal. Please view the screenshot
![screenshot_2015-11-25-19-25-52](https://cloud.githubusercontent.com/assets/15354045/11413136/a2dcb60a-93b3-11e5-9172-61973efec083.png)

**Comment by Navjotkaur12** [comment]
The Test build I have sent you was only for 30 levels , thats the reason it happened.
