### ISSUE TITLE
Game over - When the game gets over, it should be a big dialog of game over and an option to try again. Currently game gets over, there is a small text at bottom and user has no idea

### ISSUE THREAD

**Issue by prepitt** [prepitt/bubble#2]

**Comment by prepitt** [comment]
What we have now is better - however, replay doesnt work and after clicking it multiple times it goes back to the level screen. Instead - there should be a nice screen which should have replay / quit buttons, also showing remaining lives. 

We will provide the game over/ replay screens shortly.

**Comment by Navjotkaur12** [comment]
Replay Button issue is resolved. As soon as we will recieve replay screen and quit button slicing, we will be able to implement this.
